#trigger:
#  branches:
#    include:
#      - main
#  paths:
#    include:
#      - CrossPlatformAPIs/*
trigger: none
pr: none

pool:
  vmImage: windows-latest

stages:
- stage: Build_Web_App
  displayName: Build Stage

  jobs:
    - job: Build
      displayName: Build
      pool:
        name: Azure Pipelines

      steps:

      - task: UseDotNet@2
        displayName: 'Use .NET Core sdk 8.0.x'
        inputs:
          version: 8.0.x
          includePreviewVersions: true

      - task: DotNetCoreCLI@2
        displayName: 'dotnet build'
        inputs:
          projects: 'CrossPlatformAPIs/*.csproj'
          # arguments: '-c Release -o web'
          workingDirectory: CrossPlatformAPIs
      - task: DotNetCoreCLI@2
        displayName: 'dotnet publish'
        inputs:
          command: publish
          publishWebProjects: false
          projects: 'CrossPlatformAPIs/*.csproj'
          arguments: '-o $(build.artifactstagingdirectory)/web -c Release'

      - task: ArchiveFiles@2
        displayName: 'Archive CrossPlatformAPIs'
        inputs:
          rootFolderOrFile: $(build.artifactstagingdirectory)/web
          includeRootFolder: false
          archiveType: zip
          archiveFile: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
          replaceExistingArchive: true

      
      - task: PublishBuildArtifacts@1
        displayName: 'Publish cdo_framework_Cross_Platform_API_Build'
            